#
# Copyright (C) 2017 SANYO Techno Solutions Tottori Co., Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

#
# Changelog:
#
# 2018-Feb:  Add new image sensor.
#

#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += sr200pc20m_mipi_Sensor.o
